name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ SEI8uNaMeYWDgX2HWXXnXnUVUbXUWjYtBU7KR0706RHK8YkNJZGBBAtTkDpB7BnE }}
          leetcode-session: ${{ eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiNzUxOTI4NiIsIl9hdXRoX3VzZXJfYmFja2VuZCI6ImFsbGF1dGguYWNjb3VudC5hdXRoX2JhY2tlbmRzLkF1dGhlbnRpY2F0aW9uQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6IjBjNDJhY2U1MzQzNTk5MmJjZWZiOTZkMTY4NTc1OGEwNTg1ZTMyN2UiLCJpZCI6NzUxOTI4NiwiZW1haWwiOiJoa3VsYTAwNEB1Y3IuZWR1IiwidXNlcm5hbWUiOiJoa3VsYTAwNCIsInVzZXJfc2x1ZyI6ImhrdWxhMDA0IiwiYXZhdGFyIjoiaHR0cHM6Ly9hc3NldHMubGVldGNvZGUuY29tL3VzZXJzL2F2YXRhcnMvYXZhdGFyXzE2NjM5Njc5NzMucG5nIiwicmVmcmVzaGVkX2F0IjoxNjg4OTM5MjM0LCJpcCI6IjcxLjk1LjM1LjYwIiwiaWRlbnRpdHkiOiI1ZjBmZjVkODc5OWVkNGMwZWQzNTVmYTQ3NGE3YmJjMiIsInNlc3Npb25faWQiOjQyMTc1MDQ3fQ.84FCVEjSjzM1EcGz6dxyRtgsvG0-Ey8tKgC6rFs-cTI }}
          destination-folder: leetcode-solutions
